<a href="https://colab.research.google.com/github/ahmedmek1/Machine-learning-projects-sklearn/blob/main/iris__data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#import important libraries 

from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer as sms # finding the missing values and replacing it



In [28]:
#loading the data and divide it into X , Y
data_iris = load_iris()
X = data_iris.data
Y = data_iris.target
#target_names = data_iris.target_names
sm = sms(missing_values= np.nan , strategy='mean' , verbose= 0)
mx = sm.fit(X)
X = mx.transform()

In [7]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [25]:
print('the first five training examples \n' ,X[:5])
print('\nthe target of the first five training examples\n',Y[:5])
#print('\n the target names of the first five examples' , target_names[:20])

the first five training examples 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

the target of the first five training examples
 [0 0 0 0 0]

 the target names of the first five examples ['setosa' 'versicolor' 'virginica']
